import '../globals.css'
import type { Metadata } from "next";
import {Roboto,Dancing_Script} from "next/font/google";
import NavigationBar from "@/components/navbar";


const roboto = Roboto({
  variable:'--font-roboto',
  subsets:['latin']
})
const dancing =Dancing_Script({
  variable:'--font-dancing',
  subsets:['latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased scroll-smooth ${dancing.variable}`}
      >
       <NavigationBar/>
        {children}
      </body>
    </html>
  );
}
