import '../globals.css'
import type { Metadata } from "next";
import {Roboto,Dancing_Script} from "next/font/google";
import NavigationBar from "@/components/navbar";
import { Toaster } from "sonner";

const roboto = Roboto({
  variable:'--font-roboto',
  subsets:['latin']
})
const dancing =Dancing_Script({
  variable:'--font-dancing',
  subsets:['latin']
})

import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import GlobalMessageNotification from "@/components/globalmessagenotification";
import { auth } from "@/lib/auth";
import { headers } from "next/headers";
import dbConnect from "@/lib/mongodb";
import profile from "@/models/profile";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth.api.getSession({
    headers: await headers(),
  });
  
  let userProfileId = "";
  if (session?.user?.id) {
    await dbConnect();
    const userProfile = await profile.findOne({ user: session.user.id }).select("_id").lean();
    if (userProfile) userProfileId = userProfile._id.toString();
  }
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased scroll-smooth ${dancing.variable} flex flex-col min-h-screen`}
      >
       <NavigationBar/>
        <Toaster position="bottom-right" richColors />
        {userProfileId && <GlobalMessageNotification userProfileId={userProfileId} />}
        <main className="flex-1">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
